#!/usr/bin/env python3
# ruff: noqa: E501
"""Generate and run a reproducible Windows desktop-suite packaging workflow.

The script has no third-party runtime dependencies. It turns a committed TOML
manifest into project-local PyInstaller, Inno Setup, PowerShell, launcher, and
GitHub Actions files. Generated files are committed so release CI does not need
access to the skills engine.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import textwrap
import tomllib
import uuid
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

SCHEMA_VERSION = 1
GENERATED_MARKER = "Generated by desktop_suite_packager.py"
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
ID_RE = re.compile(r"^[a-z][a-z0-9_-]*$")
EXE_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


class ConfigError(ValueError):
    """Raised when a packaging manifest is unsafe or incomplete."""


@dataclass(frozen=True)
class Application:
    app_id: str
    display_name: str
    description: str
    script: str
    executable: str
    console: bool
    smoke_args: tuple[str, ...]


@dataclass(frozen=True)
class DataMapping:
    source: str
    destination: str


@dataclass(frozen=True)
class SuiteConfig:
    config_path: Path
    project_root: Path
    product: dict[str, Any]
    build: dict[str, Any]
    ci: dict[str, Any]
    applications: tuple[Application, ...]
    data: tuple[DataMapping, ...]
    manifest_hash: str

    @property
    def generated_dir(self) -> Path:
        return self.project_root / self.build["generated_dir"]

    @property
    def launcher_executable(self) -> str:
        return str(
            self.product.get("launcher_executable") or pascal_name(self.product["name"])
        )


def pascal_name(value: str) -> str:
    parts = re.findall(r"[A-Za-z0-9]+", value)
    return "".join(part[:1].upper() + part[1:] for part in parts) or "PythonSuite"


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    if not slug:
        raise ConfigError("Product name cannot be converted to a safe slug")
    return slug


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def ps_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def safe_relative(value: str, field: str, *, allow_dot: bool = False) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ConfigError(f"{field} must be a non-empty relative path")
    candidate = Path(value)
    if candidate.is_absolute() or ".." in candidate.parts:
        raise ConfigError(f"{field} must stay within the project root: {value!r}")
    normalised = candidate.as_posix()
    if normalised == "." and not allow_dot:
        raise ConfigError(f"{field} cannot be the project root")
    return normalised


def require_table(data: dict[str, Any], key: str) -> dict[str, Any]:
    value = data.get(key)
    if not isinstance(value, dict):
        raise ConfigError(f"Missing or invalid [{key}] table")
    return value


def require_text(table: dict[str, Any], key: str, section: str) -> str:
    value = table.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ConfigError(f"[{section}].{key} must be a non-empty string")
    return value.strip()


def string_list(value: Any, field: str) -> list[str]:
    if value is None:
        return []
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise ConfigError(f"{field} must be an array of strings")
    return list(value)


def command_list(value: Any) -> list[list[str]]:
    if value is None:
        return []
    if not isinstance(value, list):
        raise ConfigError("[build].quality_commands must be an array of command arrays")
    commands: list[list[str]] = []
    for index, command in enumerate(value):
        if (
            not isinstance(command, list)
            or not command
            or not all(isinstance(part, str) and part for part in command)
        ):
            raise ConfigError(
                f"[build].quality_commands[{index}] must be a non-empty array of strings"
            )
        commands.append(list(command))
    return commands


def load_config(config_path: Path) -> SuiteConfig:
    config_path = config_path.resolve()
    if not config_path.is_file():
        raise ConfigError(f"Manifest not found: {config_path}")

    raw_bytes = config_path.read_bytes()
    try:
        raw = tomllib.loads(raw_bytes.decode("utf-8"))
    except (UnicodeDecodeError, tomllib.TOMLDecodeError) as exc:
        raise ConfigError(f"Cannot parse {config_path}: {exc}") from exc

    if raw.get("schema_version") != SCHEMA_VERSION:
        raise ConfigError(f"schema_version must be {SCHEMA_VERSION}")

    root_hint = raw.get("project_root", "..")
    if not isinstance(root_hint, str) or not root_hint.strip():
        raise ConfigError("project_root must be a path relative to the manifest")
    root_path = Path(root_hint)
    if root_path.is_absolute():
        raise ConfigError("project_root must be relative to the manifest")
    project_root = (config_path.parent / root_path).resolve()
    if not project_root.is_dir():
        raise ConfigError(f"Resolved project_root is not a directory: {project_root}")
    if not config_path.is_relative_to(project_root):
        raise ConfigError("Manifest must live inside project_root")

    product = dict(require_table(raw, "product"))
    build = dict(require_table(raw, "build"))
    ci = dict(raw.get("ci", {}))

    product["name"] = require_text(product, "name", "product")
    product["slug"] = require_text(product, "slug", "product")
    product["version"] = require_text(product, "version", "product")
    product["publisher"] = require_text(product, "publisher", "product")
    product["app_id"] = require_text(product, "app_id", "product")
    if not SLUG_RE.fullmatch(product["slug"]):
        raise ConfigError(
            "[product].slug must contain lowercase letters, digits, and hyphens"
        )
    audience = str(product.get("audience", "external"))
    if audience not in {"internal", "external"}:
        raise ConfigError("[product].audience must be 'internal' or 'external'")
    product["audience"] = audience
    for field in ("license_file", "notices_file"):
        if product.get(field):
            product[field] = safe_relative(str(product[field]), f"[product].{field}")
    if product.get("icon"):
        product["icon"] = safe_relative(str(product["icon"]), "[product].icon")
    if product.get("launcher_script"):
        product["launcher_script"] = safe_relative(
            str(product["launcher_script"]), "[product].launcher_script"
        )
    launcher_exe = str(
        product.get("launcher_executable") or pascal_name(product["name"])
    )
    if not EXE_RE.fullmatch(launcher_exe):
        raise ConfigError("[product].launcher_executable is not a safe executable name")
    product["launcher_executable"] = launcher_exe

    defaults: dict[str, Any] = {
        "python_version": "3.12",
        "generated_dir": "packaging/generated",
        "work_dir": "build/desktop-suite",
        "dist_dir": "release",
        "portable_zip": True,
        "installer": True,
        "signing_required": audience == "external",
        "paths": [".", "src"],
        "hidden_imports": [],
        "collect_all": [],
        "quality_commands": [
            ["uv", "run", "--locked", "python", "-m", "pytest"]
        ],
    }
    for key, default in defaults.items():
        build.setdefault(key, default)
    for field in ("generated_dir", "work_dir", "dist_dir"):
        build[field] = safe_relative(str(build[field]), f"[build].{field}")
    build["paths"] = [
        safe_relative(path, "[build].paths", allow_dot=True)
        for path in string_list(build["paths"], "[build].paths")
    ]
    build["hidden_imports"] = string_list(
        build["hidden_imports"], "[build].hidden_imports"
    )
    build["collect_all"] = string_list(build["collect_all"], "[build].collect_all")
    build["quality_commands"] = command_list(build["quality_commands"])
    for field in ("portable_zip", "installer", "signing_required"):
        if not isinstance(build[field], bool):
            raise ConfigError(f"[build].{field} must be true or false")

    ci.setdefault("enabled", True)
    ci.setdefault("workflow_path", ".github/workflows/windows-desktop-suite.yml")
    ci.setdefault(
        "uv_sync_args",
        ["sync", "--locked", "--all-extras", "--group", "desktop-build"],
    )
    if not isinstance(ci["enabled"], bool):
        raise ConfigError("[ci].enabled must be true or false")
    ci["workflow_path"] = safe_relative(str(ci["workflow_path"]), "[ci].workflow_path")
    ci["uv_sync_args"] = string_list(ci["uv_sync_args"], "[ci].uv_sync_args")

    app_rows = raw.get("applications")
    if not isinstance(app_rows, list) or not app_rows:
        raise ConfigError("At least one [[applications]] entry is required")
    applications: list[Application] = []
    app_ids: set[str] = set()
    executable_names = {launcher_exe.casefold()}
    for index, row in enumerate(app_rows):
        if not isinstance(row, dict):
            raise ConfigError(f"applications[{index}] must be a table")
        section = f"applications[{index}]"
        app_id = require_text(row, "id", section)
        display_name = require_text(row, "display_name", section)
        script = safe_relative(
            require_text(row, "script", section), f"{section}.script"
        )
        executable = require_text(row, "executable", section)
        if not ID_RE.fullmatch(app_id):
            raise ConfigError(
                f"{section}.id must start with a letter and use safe characters"
            )
        if app_id.casefold() in app_ids:
            raise ConfigError(f"Duplicate application id: {app_id}")
        if not EXE_RE.fullmatch(executable):
            raise ConfigError(f"{section}.executable is not a safe executable name")
        if executable.casefold() in executable_names:
            raise ConfigError(f"Duplicate executable name: {executable}")
        console = row.get("console", False)
        if not isinstance(console, bool):
            raise ConfigError(f"{section}.console must be true or false")
        description = str(row.get("description", "")).strip()
        smoke_args = tuple(
            string_list(row.get("smoke_args", []), f"{section}.smoke_args")
        )
        app_ids.add(app_id.casefold())
        executable_names.add(executable.casefold())
        applications.append(
            Application(
                app_id,
                display_name,
                description,
                script,
                executable,
                console,
                smoke_args,
            )
        )

    data_rows = raw.get("data", [])
    if not isinstance(data_rows, list):
        raise ConfigError("[[data]] entries must be an array of tables")
    mappings: list[DataMapping] = []
    destinations: set[str] = set()
    for index, row in enumerate(data_rows):
        if not isinstance(row, dict):
            raise ConfigError(f"data[{index}] must be a table")
        source = safe_relative(
            require_text(row, "source", f"data[{index}]"), f"data[{index}].source"
        )
        destination = safe_relative(
            require_text(row, "destination", f"data[{index}]"),
            f"data[{index}].destination",
            allow_dot=True,
        )
        if destination.casefold() in destinations:
            raise ConfigError(f"Duplicate data destination: {destination}")
        destinations.add(destination.casefold())
        mappings.append(DataMapping(source, destination))

    return SuiteConfig(
        config_path=config_path,
        project_root=project_root,
        product=product,
        build=build,
        ci=ci,
        applications=tuple(applications),
        data=tuple(mappings),
        manifest_hash=hashlib.sha256(raw_bytes).hexdigest(),
    )


def parse_app_argument(value: str) -> tuple[str, str]:
    app_id, separator, script = value.partition("=")
    if not separator or not app_id.strip() or not script.strip():
        raise argparse.ArgumentTypeError("--app must use id=relative/path/to/entry.py")
    app_id = app_id.strip()
    if not ID_RE.fullmatch(app_id):
        raise argparse.ArgumentTypeError(f"Unsafe application id: {app_id!r}")
    try:
        script = safe_relative(script.strip(), "--app script")
    except ConfigError as exc:
        raise argparse.ArgumentTypeError(str(exc)) from exc
    return app_id, script


def init_manifest(args: argparse.Namespace) -> int:
    project_root = args.project_root.resolve()
    if not project_root.is_dir():
        raise ConfigError(f"Project root is not a directory: {project_root}")
    manifest = project_root / "packaging" / "desktop-suite.toml"
    if manifest.exists() and not args.force:
        raise ConfigError(
            f"Manifest already exists: {manifest}; use --force to replace it"
        )
    manifest.parent.mkdir(parents=True, exist_ok=True)

    slug = args.slug or slugify(args.product_name)
    launcher = pascal_name(args.product_name)
    lines = [
        f"schema_version = {SCHEMA_VERSION}",
        'project_root = ".."',
        "",
        "[product]",
        f"name = {toml_string(args.product_name)}",
        f"slug = {toml_string(slug)}",
        f"version = {toml_string(args.version)}",
        f"publisher = {toml_string(args.publisher)}",
        f"app_id = {toml_string('{' + str(uuid.uuid4()).upper() + '}')}",
        f"launcher_executable = {toml_string(launcher)}",
        '# launcher_script = "index-app.py"  # Reuse an existing frozen-safe launcher.',
        f"audience = {toml_string(args.audience)}",
        'license_file = "LICENSE"',
        'notices_file = "THIRD_PARTY_NOTICES.md"',
        'icon = ""',
        "",
        "[build]",
        'python_version = "3.12"',
        'generated_dir = "packaging/generated"',
        'work_dir = "build/desktop-suite"',
        'dist_dir = "release"',
        "portable_zip = true",
        "installer = true",
        f"signing_required = {'true' if args.audience == 'external' else 'false'}",
        'paths = [".", "src"]',
        "hidden_imports = []",
        "collect_all = []",
        'quality_commands = [["uv", "run", "--locked", "python", "-m", "pytest"]]',
        "",
        "[ci]",
        "enabled = true",
        'workflow_path = ".github/workflows/windows-desktop-suite.yml"',
        'uv_sync_args = ["sync", "--locked", "--all-extras", "--group", "desktop-build"]',
    ]
    for app_id, script in args.app:
        display = app_id.replace("_", " ").replace("-", " ").title()
        lines.extend(
            [
                "",
                "[[applications]]",
                f"id = {toml_string(app_id)}",
                f"display_name = {toml_string(display)}",
                'description = ""',
                f"script = {toml_string(script)}",
                f"executable = {toml_string(pascal_name(display))}",
                "console = false",
                "smoke_args = []",
            ]
        )
    lines.extend(
        [
            "",
            "# Add one block per resource directory or file.",
            "# [[data]]",
            '# source = "templates"',
            '# destination = "templates"',
            "",
        ]
    )
    manifest.write_text("\n".join(lines), encoding="utf-8")
    print(f"Created {manifest}")
    print(
        "Edit display names, descriptions, console modes, data mappings, and release metadata."
    )
    return 0


def generated_header(config: SuiteConfig, comment: str = "#") -> str:
    rel = config.config_path.relative_to(config.project_root).as_posix()
    return (
        f"{comment} {GENERATED_MARKER}; source={rel}; sha256={config.manifest_hash}\n"
    )


def launcher_source(config: SuiteConfig) -> str:
    apps = [
        {
            "id": app.app_id,
            "display_name": app.display_name,
            "description": app.description,
            "executable": app.executable,
        }
        for app in config.applications
    ]
    return generated_header(config) + textwrap.dedent(
        f'''\
        """Generated launcher for {config.product["name"]}."""

        from __future__ import annotations

        import subprocess
        import sys
        import tkinter as tk
        from pathlib import Path
        from tkinter import messagebox, ttk

        PRODUCT_NAME = {config.product["name"]!r}
        APPLICATIONS = {apps!r}


        def installed_directory() -> Path:
            return Path(sys.executable).resolve().parent


        def executable_path(name: str) -> Path:
            suffix = ".exe" if sys.platform == "win32" else ""
            return installed_directory() / f"{{name}}{{suffix}}"


        def launch(application: dict[str, str]) -> None:
            target = executable_path(application["executable"])
            if not target.is_file():
                messagebox.showerror(PRODUCT_NAME, f"Installed tool is missing:\\n{{target}}")
                return
            try:
                subprocess.Popen([str(target)], cwd=str(installed_directory()), shell=False)
            except OSError as exc:
                messagebox.showerror(PRODUCT_NAME, f"Could not start {{application['display_name']}}:\\n{{exc}}")


        def main() -> int:
            root = tk.Tk()
            root.title(PRODUCT_NAME)
            root.minsize(520, 260)
            frame = ttk.Frame(root, padding=24)
            frame.grid(sticky="nsew")
            root.columnconfigure(0, weight=1)
            root.rowconfigure(0, weight=1)
            frame.columnconfigure(0, weight=1)

            ttk.Label(frame, text=PRODUCT_NAME, font=("TkDefaultFont", 18, "bold")).grid(
                row=0, column=0, sticky="w", pady=(0, 16)
            )
            for row, application in enumerate(APPLICATIONS, start=1):
                card = ttk.Frame(frame, padding=(0, 8))
                card.grid(row=row, column=0, sticky="ew")
                card.columnconfigure(0, weight=1)
                ttk.Label(card, text=application["display_name"], font=("TkDefaultFont", 11, "bold")).grid(
                    row=0, column=0, sticky="w"
                )
                if application["description"]:
                    ttk.Label(card, text=application["description"], wraplength=360).grid(
                        row=1, column=0, sticky="w", pady=(2, 0)
                    )
                ttk.Button(card, text="Open", command=lambda app=application: launch(app)).grid(
                    row=0, column=1, rowspan=2, padx=(16, 0)
                )

            root.mainloop()
            return 0


        if __name__ == "__main__":
            raise SystemExit(main())
        '''
    )


def spec_source(config: SuiteConfig) -> str:
    rel_root = os.path.relpath(config.project_root, config.generated_dir).replace(
        "\\", "/"
    )
    launcher_script = config.product.get("launcher_script")
    launcher_expr = (
        f"PROJECT_ROOT / {launcher_script!r}"
        if launcher_script
        else "SPECPATH_PATH / 'suite_launcher.py'"
    )
    paths = [f"PROJECT_ROOT / {path!r}" for path in config.build["paths"]]
    data_rows = [
        f"(str(PROJECT_ROOT / {item.source!r}), {item.destination!r})"
        for item in config.data
    ]
    icon = config.product.get("icon")
    icon_expr = f"str(PROJECT_ROOT / {icon!r})" if icon else "None"
    analyses: list[str] = []
    executables: list[str] = []
    collection_items: list[str] = []

    entries = [
        (
            "launcher",
            launcher_expr,
            config.launcher_executable,
            False,
        ),
        *[
            (
                f"app_{index}",
                f"PROJECT_ROOT / {app.script!r}",
                app.executable,
                app.console,
            )
            for index, app in enumerate(config.applications)
        ],
    ]
    for index, (variable, script_expr, executable, console) in enumerate(entries):
        datas_expr = "shared_datas" if index == 0 else "[]"
        binaries_expr = "shared_binaries" if index == 0 else "[]"
        analyses.append(
            textwrap.dedent(
                f"""\
                {variable}_a = Analysis(
                    [str({script_expr})],
                    pathex=[str(path) for path in project_paths],
                    binaries={binaries_expr},
                    datas={datas_expr},
                    hiddenimports=shared_hiddenimports,
                    hookspath=[],
                    hooksconfig={{}},
                    runtime_hooks=[],
                    excludes=[],
                    noarchive=False,
                    optimize=0,
                )
                {variable}_pyz = PYZ({variable}_a.pure)
                {variable}_exe = EXE(
                    {variable}_pyz,
                    {variable}_a.scripts,
                    [],
                    exclude_binaries=True,
                    name={executable!r},
                    debug=False,
                    bootloader_ignore_signals=False,
                    strip=False,
                    upx=False,
                    console={console!r},
                    disable_windowed_traceback=False,
                    argv_emulation=False,
                    target_arch=None,
                    codesign_identity=None,
                    entitlements_file=None,
                    icon={icon_expr},
                    contents_directory="_internal",
                )
                """
            )
        )
        executables.append(f"{variable}_exe")
        collection_items.extend([f"{variable}_a.binaries", f"{variable}_a.datas"])

    collect_packages = repr(config.build["collect_all"])
    hidden_imports = repr(config.build["hidden_imports"])
    return (
        generated_header(config)
        + textwrap.dedent(
            f"""\
        from pathlib import Path

        from PyInstaller.utils.hooks import collect_all

        SPECPATH_PATH = Path(SPECPATH).resolve()
        PROJECT_ROOT = (SPECPATH_PATH / {rel_root!r}).resolve()
        project_paths = [{", ".join(paths)}]
        shared_datas = [{", ".join(data_rows)}]
        shared_binaries = []
        shared_hiddenimports = list({hidden_imports})

        for package_name in {collect_packages}:
            package_datas, package_binaries, package_hiddenimports = collect_all(package_name)
            shared_datas.extend(package_datas)
            shared_binaries.extend(package_binaries)
            shared_hiddenimports.extend(package_hiddenimports)

        """
        )
        + "\n".join(analyses)
        + textwrap.dedent(
            f"""\
        suite = COLLECT(
            {", ".join(executables)},
            {", ".join(collection_items)},
            strip=False,
            upx=False,
            upx_exclude=[],
            name={config.product["slug"]!r},
        )
        """
        )
    )


def inno_source(config: SuiteConfig) -> str:
    rel_root = os.path.relpath(config.project_root, config.generated_dir).replace(
        "/", "\\"
    )
    dist_dir = str(config.build["dist_dir"]).replace("/", "\\")
    slug = config.product["slug"]
    setup_name = f"{slug}-Setup-{config.product['version']}"
    icon = config.product.get("icon")
    license_file = config.product.get("license_file")
    optional_lines = []
    if icon:
        icon_windows = icon.replace("/", "\\")
        optional_lines.append(f"SetupIconFile={{#ProjectRoot}}\\{icon_windows}")
    if license_file:
        license_windows = license_file.replace("/", "\\")
        optional_lines.append(f"LicenseFile={{#ProjectRoot}}\\{license_windows}")
    return (
        generated_header(config, ";")
        + textwrap.dedent(
            rf"""
        #define ProjectRoot "{rel_root}"
        #define ProductName "{config.product["name"]}"
        #define ProductVersion "{config.product["version"]}"
        #define Publisher "{config.product["publisher"]}"
        #define Launcher "{config.launcher_executable}.exe"

        [Setup]
        AppId={config.product["app_id"]}
        AppName={{#ProductName}}
        AppVersion={{#ProductVersion}}
        AppPublisher={{#Publisher}}
        DefaultDirName={{localappdata}}\Programs\{{#ProductName}}
        DefaultGroupName={{#ProductName}}
        UninstallDisplayIcon={{app}}\{{#Launcher}}
        OutputDir={{#ProjectRoot}}\{dist_dir}
        OutputBaseFilename={setup_name}
        Compression=lzma2
        SolidCompression=yes
        WizardStyle=modern
        PrivilegesRequired=lowest
        ArchitecturesAllowed=x64compatible
        ArchitecturesInstallIn64BitMode=x64compatible
        DisableProgramGroupPage=yes
        {os.linesep.join(optional_lines)}

        [Files]
        Source: "{{#ProjectRoot}}\{dist_dir}\stage\{slug}\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs

        [Icons]
        Name: "{{autoprograms}}\{{#ProductName}}"; Filename: "{{app}}\{{#Launcher}}"
        Name: "{{autodesktop}}\{{#ProductName}}"; Filename: "{{app}}\{{#Launcher}}"; Tasks: desktopicon

        [Tasks]
        Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional shortcuts:"

        [Run]
        Filename: "{{app}}\{{#Launcher}}"; Description: "Open {{#ProductName}}"; Flags: nowait postinstall skipifsilent
        """
        ).lstrip()
    )


def powershell_source(config: SuiteConfig) -> str:
    manifest_rel = (
        config.config_path.relative_to(config.project_root)
        .as_posix()
        .replace("/", "\\")
    )
    spec_rel = (
        (config.generated_dir / f"{config.product['slug']}.spec")
        .relative_to(config.project_root)
        .as_posix()
        .replace("/", "\\")
    )
    iss_rel = (
        (config.generated_dir / f"{config.product['slug']}.iss")
        .relative_to(config.project_root)
        .as_posix()
        .replace("/", "\\")
    )
    dist_dir = str(config.build["dist_dir"]).replace("/", "\\")
    work_dir = str(config.build["work_dir"]).replace("/", "\\")
    sync_call = " ".join(ps_quote(part) for part in config.ci["uv_sync_args"])
    quality_lines: list[str] = []
    for index, command in enumerate(config.build["quality_commands"], start=1):
        invocation = " ".join(ps_quote(part) for part in command)
        quality_lines.extend(
            [
                f"    Write-Host 'Quality command {index}: {' '.join(command)}'",
                f"    & {invocation}",
                f"    if ($LASTEXITCODE -ne 0) {{ throw 'Quality command {index} failed.' }}",
            ]
        )
    expected_exes = [
        config.launcher_executable,
        *[app.executable for app in config.applications],
    ]
    exe_checks = "\n".join(
        f"Assert-File (Join-Path $suiteDir {ps_quote(name + '.exe')})"
        for name in expected_exes
    )
    data_check_rows = []
    for item in config.data:
        destination = item.destination.replace("/", "\\")
        data_check_rows.append(
            f"Assert-Path (Join-Path (Join-Path $suiteDir '_internal') {ps_quote(destination)})"
        )
    data_checks = "\n".join(data_check_rows)
    smoke_blocks: list[str] = []
    for app in config.applications:
        if not app.smoke_args:
            continue
        arg_list = ", ".join(ps_quote(arg) for arg in app.smoke_args)
        smoke_blocks.append(
            textwrap.dedent(
                f"""\
                $smokeProcess = Start-Process -FilePath (Join-Path $suiteDir {ps_quote(app.executable + ".exe")}) -ArgumentList @({arg_list}) -PassThru -Wait
                if ($smokeProcess.ExitCode -ne 0) {{ throw {ps_quote("Smoke test failed for " + app.executable)} }}
                $smokeResults += [ordered]@{{ application = {ps_quote(app.app_id)}; result = 'passed'; exit_code = $smokeProcess.ExitCode }}
                """
            ).strip()
        )
    signing_required = "$true" if config.build["signing_required"] else "$false"
    portable = "$true" if config.build["portable_zip"] else "$false"
    installer = "$true" if config.build["installer"] else "$false"
    setup_name = f"{config.product['slug']}-Setup-{config.product['version']}.exe"
    quality_body = os.linesep.join(quality_lines)
    if not quality_body:
        quality_body = "        Write-Host 'No quality commands configured.'"
    return (
        generated_header(config)
        + textwrap.dedent(
            rf"""
        [CmdletBinding()]
        param(
            [switch]$UnsignedDevelopmentBuild,
            [switch]$SkipTests,
            [switch]$SkipInstaller
        )

        $ErrorActionPreference = 'Stop'
        Set-StrictMode -Version Latest
        $projectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
        $manifest = Join-Path $projectRoot {ps_quote(manifest_rel)}
        $expectedManifestHash = {ps_quote(config.manifest_hash.upper())}
        $actualManifestHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $manifest).Hash
        if ($actualManifestHash -ne $expectedManifestHash) {{
            throw 'desktop-suite.toml changed. Regenerate packaging files before building.'
        }}

        function Assert-Path([string]$Path) {{
            if (-not (Test-Path -LiteralPath $Path)) {{ throw "Required bundle path is missing: $Path" }}
        }}

        function Assert-File([string]$Path) {{
            if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {{ throw "Required bundle file is missing: $Path" }}
        }}

        function Find-SignTool {{
            $command = Get-Command 'signtool.exe' -ErrorAction SilentlyContinue
            if ($command) {{ return $command.Source }}
            return $null
        }}

        function Sign-Artifact([string]$Path, [string]$SignTool) {{
            & $SignTool sign /sha1 $env:WINDOWS_CERT_SHA1 /fd SHA256 /tr $env:WINDOWS_TIMESTAMP_URL /td SHA256 $Path
            if ($LASTEXITCODE -ne 0) {{ throw "Signing failed: $Path" }}
            & $SignTool verify /pa $Path
            if ($LASTEXITCODE -ne 0) {{ throw "Signature verification failed: $Path" }}
        }}

        Push-Location $projectRoot
        try {{
            if (-not (Get-Command 'uv' -ErrorAction SilentlyContinue)) {{ throw 'uv is required for locked release builds.' }}
            & 'uv' {sync_call}
            if ($LASTEXITCODE -ne 0) {{ throw 'uv sync failed.' }}

            if (-not $SkipTests) {{
        {quality_body}
            }}

            $distDir = Join-Path $projectRoot {ps_quote(dist_dir)}
            $stageDir = Join-Path $distDir 'stage'
            $workDir = Join-Path $projectRoot {ps_quote(work_dir)}
            if (Test-Path -LiteralPath $stageDir) {{ Remove-Item -LiteralPath $stageDir -Recurse -Force }}
            if (Test-Path -LiteralPath $workDir) {{ Remove-Item -LiteralPath $workDir -Recurse -Force }}
            New-Item -ItemType Directory -Force -Path $distDir | Out-Null

            & 'uv' 'run' '--locked' 'python' '-m' 'PyInstaller' (Join-Path $projectRoot {ps_quote(spec_rel)}) '--noconfirm' '--clean' '--distpath' $stageDir '--workpath' $workDir
            if ($LASTEXITCODE -ne 0) {{ throw 'PyInstaller build failed.' }}

            $suiteDir = Join-Path $stageDir {ps_quote(config.product["slug"])}
            Assert-Path $suiteDir
        {textwrap.indent(exe_checks, "    ")}
        {textwrap.indent(data_checks, "    ") if data_checks else ""}

            $smokeResults = @()
        {textwrap.indent(os.linesep.join(smoke_blocks), "    ") if smoke_blocks else "    $smokeResults += [ordered]@{ application = 'interactive-applications'; result = 'manual-check-required'; exit_code = $null }"}

            $signingRequired = {signing_required}
            $signed = $false
            if ($signingRequired -and -not $UnsignedDevelopmentBuild) {{
                if (-not $env:WINDOWS_CERT_SHA1 -or -not $env:WINDOWS_TIMESTAMP_URL) {{
                    throw 'Signing is required. Set WINDOWS_CERT_SHA1 and WINDOWS_TIMESTAMP_URL.'
                }}
                $signTool = Find-SignTool
                if (-not $signTool) {{ throw 'signtool.exe was not found.' }}
                Get-ChildItem -LiteralPath $suiteDir -Filter '*.exe' -File | ForEach-Object {{ Sign-Artifact $_.FullName $signTool }}
                $signed = $true
            }} elseif ($signingRequired) {{
                Write-Warning 'Unsigned development build: do not publish these artifacts.'
            }}

            if ({portable}) {{
                $zipPath = Join-Path $distDir {ps_quote(config.product["slug"] + "-" + config.product["version"] + "-windows-x64.zip")}
                if (Test-Path -LiteralPath $zipPath) {{ Remove-Item -LiteralPath $zipPath -Force }}
                Compress-Archive -Path (Join-Path $suiteDir '*') -DestinationPath $zipPath -CompressionLevel Optimal
            }}

            $installerPath = $null
            if ({installer} -and -not $SkipInstaller) {{
                $isccCommand = Get-Command 'ISCC.exe' -ErrorAction SilentlyContinue
                $iscc = if ($isccCommand) {{ $isccCommand.Source }} else {{ $null }}
                if (-not $iscc) {{
                    $candidates = @(
                        "${{env:ProgramFiles(x86)}}\Inno Setup 6\ISCC.exe",
                        "$env:ProgramFiles\Inno Setup 6\ISCC.exe",
                        "$env:ProgramFiles\Inno Setup 7\ISCC.exe"
                    )
                    $iscc = $candidates | Where-Object {{ $_ -and (Test-Path -LiteralPath $_) }} | Select-Object -First 1
                }}
                if (-not $iscc) {{ throw 'Inno Setup compiler ISCC.exe was not found.' }}
                & $iscc (Join-Path $projectRoot {ps_quote(iss_rel)})
                if ($LASTEXITCODE -ne 0) {{ throw 'Inno Setup compilation failed.' }}
                $installerPath = Join-Path $distDir {ps_quote(setup_name)}
                Assert-File $installerPath
                if ($signingRequired -and -not $UnsignedDevelopmentBuild) {{ Sign-Artifact $installerPath $signTool }}
            }}

            $artifactRows = Get-ChildItem -LiteralPath $distDir -File | ForEach-Object {{
                [ordered]@{{ name = $_.Name; bytes = $_.Length; sha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $_.FullName).Hash.ToLowerInvariant() }}
            }}
            $evidence = [ordered]@{{
                schema_version = 1
                product = {ps_quote(config.product["name"])}
                version = {ps_quote(config.product["version"])}
                manifest_sha256 = $actualManifestHash.ToLowerInvariant()
                generated_utc = [DateTime]::UtcNow.ToString('o')
                python = (& 'uv' 'run' '--locked' 'python' '--version' 2>&1 | Out-String).Trim()
                pyinstaller = (& 'uv' 'run' '--locked' 'python' '-m' 'PyInstaller' '--version' 2>&1 | Out-String).Trim()
                signed = $signed
                unsigned_development_build = [bool]$UnsignedDevelopmentBuild
                smoke = $smokeResults
                artifacts = @($artifactRows)
            }}
            $evidence | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath (Join-Path $distDir 'desktop-suite-evidence.json') -Encoding utf8
            Write-Host "Desktop suite build completed: $distDir"
        }} finally {{
            Pop-Location
        }}
        """
        ).lstrip()
    )


def workflow_source(config: SuiteConfig) -> str:
    script_rel = "scripts/build-desktop-suite.ps1"
    dist_dir = config.build["dist_dir"].replace("\\", "/")
    return generated_header(config) + textwrap.dedent(
        f"""\
        name: Windows desktop suite

        on:
          workflow_dispatch:
          pull_request:
          push:
            branches: [main]

        permissions:
          contents: read

        jobs:
          verify-package:
            runs-on: windows-latest
            steps:
              - uses: actions/checkout@v6
              - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
                with:
                  python-version: {config.build["python_version"]!r}
                  enable-cache: true
              - name: Build unsigned verification bundle
                shell: powershell
                run: ./{script_rel} -UnsignedDevelopmentBuild -SkipInstaller
              - name: Upload verification artifacts
                uses: actions/upload-artifact@v7
                with:
                  name: {config.product["slug"]}-windows-verification
                  path: |
                    {dist_dir}/*.zip
                    {dist_dir}/desktop-suite-evidence.json
                  if-no-files-found: error
        """
    )


def write_generated(path: Path, content: str, *, force: bool) -> None:
    if path.exists():
        existing = path.read_text(encoding="utf-8", errors="replace")
        if GENERATED_MARKER not in existing and not force:
            raise ConfigError(f"Refusing to overwrite non-generated file: {path}")
        if existing == content:
            return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.replace("\r\n", "\n"), encoding="utf-8", newline="\n")


def generate_project_files(config: SuiteConfig, *, force: bool = False) -> list[Path]:
    config.generated_dir.mkdir(parents=True, exist_ok=True)
    outputs = {
        config.generated_dir / f"{config.product['slug']}.spec": spec_source(config),
        config.generated_dir / f"{config.product['slug']}.iss": inno_source(config),
        config.project_root / "scripts" / "build-desktop-suite.ps1": powershell_source(
            config
        ),
    }
    if not config.product.get("launcher_script"):
        outputs[config.generated_dir / "suite_launcher.py"] = launcher_source(config)
    if config.ci["enabled"]:
        outputs[config.project_root / config.ci["workflow_path"]] = workflow_source(
            config
        )
    for path, content in outputs.items():
        write_generated(path, content, force=force)
    hash_path = config.generated_dir / "manifest.sha256"
    hash_path.write_text(config.manifest_hash + "\n", encoding="ascii")
    paths = [*outputs, hash_path]
    for path in paths:
        print(f"Generated {path.relative_to(config.project_root)}")
    return paths


def scan_source(path: Path) -> list[tuple[str, str]]:
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return [("warning", "entry script is not UTF-8; static packaging scan skipped")]
    findings: list[tuple[str, str]] = []
    if "shell=True" in text or "shell = True" in text:
        findings.append(
            ("error", "uses shell=True; replace with an argument array and shell=False")
        )
    if re.search(
        r"sys\.executable.{0,240}[\"'][^\"']+\.py[\"']",
        text,
        flags=re.DOTALL,
    ):
        findings.append(
            (
                "warning",
                "combines sys.executable with a .py path; frozen builds may relaunch themselves",
            )
        )
    if re.search(r"host\s*=\s*[\"']0\.0\.0\.0[\"']", text) and re.search(
        r"debug\s*=\s*True", text
    ):
        findings.append(
            (
                "error",
                "runs a debug web server on 0.0.0.0; bind local tools to 127.0.0.1 with debug off",
            )
        )
    if re.search(r"(?:pip|uv)\s+install", text) and (
        "subprocess" in text or "os.system" in text
    ):
        findings.append(
            (
                "warning",
                "appears to install dependencies at runtime; install them during the release build",
            )
        )
    return findings


def doctor(config: SuiteConfig, *, json_output: bool = False) -> int:
    checks: list[dict[str, str]] = []

    def add(level: str, subject: str, message: str) -> None:
        checks.append({"level": level, "subject": subject, "message": message})

    launcher_script = config.product.get("launcher_script")
    if launcher_script:
        launcher_path = config.project_root / launcher_script
        if launcher_path.is_file():
            add("pass", "launcher", f"existing launcher found: {launcher_script}")
            for level, message in scan_source(launcher_path):
                add(level, "launcher", message)
        else:
            add("error", "launcher", f"existing launcher not found: {launcher_script}")

    for app in config.applications:
        script_path = config.project_root / app.script
        if not script_path.is_file():
            add("error", app.app_id, f"entry script not found: {app.script}")
            continue
        add("pass", app.app_id, f"entry script found: {app.script}")
        for level, message in scan_source(script_path):
            add(level, app.app_id, message)

    for mapping in config.data:
        path = config.project_root / mapping.source
        add(
            "pass" if path.exists() else "error",
            "data",
            f"{mapping.source} -> {mapping.destination}: {'found' if path.exists() else 'missing'}",
        )

    icon = config.product.get("icon")
    if icon:
        path = config.project_root / icon
        add(
            "pass" if path.is_file() else "error",
            "icon",
            f"{icon}: {'found' if path.is_file() else 'missing'}",
        )

    if config.product["audience"] == "external":
        for field in ("license_file", "notices_file"):
            value = config.product.get(field)
            if not value:
                add(
                    "error",
                    "legal",
                    f"[product].{field} is required for external distribution",
                )
            else:
                path = config.project_root / value
                add(
                    "pass" if path.is_file() else "error",
                    "legal",
                    f"{value}: {'found' if path.is_file() else 'missing'}",
                )

    if shutil.which("uv"):
        add("pass", "tool", "uv found")
    else:
        add("error", "tool", "uv not found")
    if os.name == "nt":
        if shutil.which("powershell") or shutil.which("pwsh"):
            add("pass", "tool", "PowerShell found")
        else:
            add("error", "tool", "PowerShell not found")
        if config.build["installer"]:
            add(
                "pass" if find_iscc() else "warning",
                "tool",
                "Inno Setup compiler found"
                if find_iscc()
                else "Inno Setup compiler not found; installer build will fail",
            )
    else:
        add(
            "warning",
            "platform",
            "Windows artifacts must be built and tested on Windows",
        )

    errors = sum(item["level"] == "error" for item in checks)
    warnings = sum(item["level"] == "warning" for item in checks)
    if json_output:
        print(
            json.dumps(
                {"errors": errors, "warnings": warnings, "checks": checks}, indent=2
            )
        )
    else:
        for item in checks:
            print(f"{item['level'].upper():7} {item['subject']}: {item['message']}")
        print(f"Doctor result: {errors} error(s), {warnings} warning(s)")
    return 1 if errors else 0


def find_iscc() -> str | None:
    direct = shutil.which("ISCC.exe") or shutil.which("iscc")
    if direct:
        return direct
    if os.name != "nt":
        return None
    roots = [os.environ.get("PROGRAMFILES(X86)"), os.environ.get("PROGRAMFILES")]
    for root in filter(None, roots):
        for version in ("Inno Setup 7", "Inno Setup 6"):
            candidate = Path(root) / version / "ISCC.exe"
            if candidate.is_file():
                return str(candidate)
    return None


def run_build(args: argparse.Namespace) -> int:
    config = load_config(args.config)
    generate_project_files(config, force=args.force_generated)
    shell = shutil.which("pwsh") or shutil.which("powershell")
    if not shell:
        raise ConfigError("PowerShell is required to run the generated Windows build")
    command = [
        shell,
        "-NoProfile",
        "-ExecutionPolicy",
        "Bypass",
        "-File",
        str(config.project_root / "scripts" / "build-desktop-suite.ps1"),
    ]
    if args.unsigned_development_build:
        command.append("-UnsignedDevelopmentBuild")
    if args.skip_tests:
        command.append("-SkipTests")
    if args.skip_installer:
        command.append("-SkipInstaller")
    completed = subprocess.run(command, cwd=config.project_root, check=False)  # noqa: S603
    return completed.returncode


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate reproducible PyInstaller desktop-suite release files."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    init = subparsers.add_parser("init", help="Create packaging/desktop-suite.toml")
    init.add_argument("--project-root", type=Path, required=True)
    init.add_argument("--product-name", required=True)
    init.add_argument("--publisher", required=True)
    init.add_argument("--version", default="0.1.0")
    init.add_argument("--slug")
    init.add_argument(
        "--audience", choices=("internal", "external"), default="external"
    )
    init.add_argument("--app", action="append", required=True, type=parse_app_argument)
    init.add_argument("--force", action="store_true")
    init.set_defaults(func=init_manifest)

    generate = subparsers.add_parser(
        "generate", help="Generate project-local release files"
    )
    generate.add_argument("--config", type=Path, required=True)
    generate.add_argument(
        "--force", action="store_true", help="Replace conflicting generated targets"
    )
    generate.set_defaults(
        func=lambda args: (
            generate_project_files(load_config(args.config), force=args.force) and 0
        )
    )

    check = subparsers.add_parser(
        "doctor", help="Validate manifest, source risks, and build tools"
    )
    check.add_argument("--config", type=Path, required=True)
    check.add_argument("--json", action="store_true")
    check.set_defaults(
        func=lambda args: doctor(load_config(args.config), json_output=args.json)
    )

    build = subparsers.add_parser(
        "build", help="Generate files and run the Windows build"
    )
    build.add_argument("--config", type=Path, required=True)
    build.add_argument("--unsigned-development-build", action="store_true")
    build.add_argument("--skip-tests", action="store_true")
    build.add_argument("--skip-installer", action="store_true")
    build.add_argument("--force-generated", action="store_true")
    build.set_defaults(func=run_build)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return int(args.func(args))
    except ConfigError as exc:
        parser.error(str(exc))
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
